python main.py --msg 'seed' --batch_size 26 --seed 1
python main.py --msg 'seed' --batch_size 26 --seed 2
python main.py --msg 'seed' --batch_size 26 --seed 3
python main.py --msg 'seed' --batch_size 26 --seed 4
python main.py --msg 'seed' --batch_size 26 --seed 5
python main.py --msg 'seed' --batch_size 26 --seed 6
python main.py --msg 'seed' --batch_size 26 --seed 7
python main.py --msg 'seed' --batch_size 26 --seed 8
python main.py --msg 'seed' --batch_size 26 --seed 9
python main.py --msg 'seed' --batch_size 26 --seed 10
python main.py --msg 'seed' --batch_size 26 --seed 11
python main.py --msg 'seed' --batch_size 26 --seed 12
python main.py --msg 'seed' --batch_size 26 --seed 13
python main.py --msg 'seed' --batch_size 26 --seed 14
python main.py --msg 'seed' --batch_size 26 --seed 15